package array

/**
 * 389. Find the Difference
 *
 * You are given two strings s and t.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Return the letter that was added to t.
 *
 * Example 1:
 *
 * Input: s = "abcd", t = "abcde"
 *
 * Output: "e"
 *
 * Explanation: 'e' is the letter that was added.
 *
 *
 * Example 2:
 *
 * Input: s = "", t = "y"
 *
 * Output: "y"
 *
 *
 *
 * Constraints:
 *
 * 0 <= s.length <= 1000
 * t.length == s.length + 1
 * s and t consist of lowercase English letters.
 */
class FindTheDifference_389 {

    companion object {

        @JvmStatic
        fun main(args: Array<String>) {
            println(FindTheDifference_389().findTheDifference2("abcd", "abcde"))
            println(FindTheDifference_389().findTheDifference2("", "a"))
        }

    }

    fun findTheDifference(s: String, t: String): Char {

        val iArr = IntArray(26) { 0 }

        for (i in 0..s.lastIndex) {
            iArr[t[i] - 'a'] = iArr[t[i] - 'a'] + 1
            iArr[s[i] - 'a'] = iArr[s[i] - 'a'] - 1
        }
        iArr[t[s.length] - 'a'] = iArr[t[s.length] - 'a'] + 1

        val rx = 'a' + iArr.indexOf(1)

        return rx

    }


    fun findTheDifference2(s: String, t: String): Char {
        var sum = t[0]
        for (i in 0..s.lastIndex) {
            sum += t[i + 1] - s[i]
        }
        return sum
    }
}